operatorNamespace: rook-ceph
cephClusterSpec:
  mon:
    allowMultiplePerNode: true
cephBlockPools:
- name: ceph-blockpool
  spec:
    failureDomain: host
    replicated:
      size: 2
  storageClass:
    allowVolumeExpansion: true
    allowedTopologies: []
    enabled: true
    isDefault: true
    mountOptions: []
    name: ceph-block
    parameters:
      csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/controller-expand-secret-namespace: '{{ .Release.Namespace
        }}'
      csi.storage.k8s.io/fstype: ext4
      csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
      csi.storage.k8s.io/node-stage-secret-namespace: '{{ .Release.Namespace }}'
      csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/provisioner-secret-namespace: '{{ .Release.Namespace }}'
      imageFeatures: layering
      imageFormat: "2"
    reclaimPolicy: Delete
    volumeBindingMode: Immediate